stages:
  - test

test:
  stage: test
  script:
  - apt-get update
  - apt-get install -y gettext
  - pip install -r requirements.txt
  - pip install coverage
  - ./manage.py compilemessages
  - coverage run ./manage.py test
  - coverage html
  - coverage report
  artifacts:
    paths:
      - coverage_report/

linting:
  stage: test
  script:
    - pip install black flake8
    - black --check .
    - flake8 .
