stages:
  - test

test:
  stage: test
  script:
  - apt-get update
  - apt-get install -y gettext python3-xapian libgraphviz-dev
  - pushd /usr/lib/python3/dist-packages/xapian && ln -s _xapian* _xapian.so && popd
  - export PYTHONPATH="/usr/lib/python3/dist-packages:$PYTHONPATH"
  - python -c 'import xapian' # Fail immediately if there is a problem with xapian
  - pip install -r requirements.txt
  - pip install coverage
  - ./manage.py compilemessages
  - coverage run ./manage.py test
  - coverage html
  - coverage report
  - cd doc
  - make html # Make documentation
  artifacts:
    paths:
      - coverage_report/

black:
  stage: test
  script:
    - pip install black
    - black --check .
