# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0032_auto_20190909_0043")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("MAN", "Man"), ("WOMAN", "Woman")],
                max_length=10,
                null=True,
                verbose_name="sex",
            ),
        )
    ]
